### ISSUE TITLE
Allow user to set font color

### ISSUE THREAD

**Issue by gregbartell** [TheoBr/inSquare#5]
Not totally sure how to take user input yet, but the user should definitely be able to change the color of the watch face by himself.

**Comment by t3dotgg** [comment]
This should be done through a "settings" screen in the Pebble Android/iOS app. I'll show you in person and try to find some code that's already done it. I may have to handle this since you don't have a pebble of your own, but getting the emulator to work with the link I showed you should work as well

**Comment by t3dotgg** [comment]
I have no idea how we'll debug this without an actual Pebble Time...

**Comment by t3dotgg** [comment]
Better yet, let users choose the background color too, and we can just make the frame color the same as the text color, and handle split accordingly as well. This could be REALLY cool

**Comment by t3dotgg** [comment]
Closing for separate inColor repo
